version: "3"

services:
  drupal:
    image: drupal:7.72-apache
    ports:
      - "80:80"
    volumes:
    - ./repos:/mnt/h5pdev
    - drupal-storage:/var/www/html
  db:
    image: mysql:5.7
    volumes:
      - db-storage:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal

volumes:
  drupal-storage:
  db-storage:

